language: cpp

sudo: false

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLLVM_TARGETS_TO_BUILD="all" -G "Unix Makefiles" ..
  - make -j 8

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  include:
    - if: branch = master
      os: osx
      compiler: clang
      script: brew update && brew install --HEAD keystone
    - if: branch = master
      os: osx
      compiler: gcc
      script: brew update && brew install --HEAD keystone
